name: update-receptor

on:
  repository_dispatch:
    types: [ping]

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Main repo checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Submodule update
        run: |
          git submodule update --remote ${{ github.event.client_payload.smd_name }}
          git add ${{ github.event.client_payload.smd_name }}        
          git config --global user.name ${{ github.event.client_payload.user_name }}
          git config --global user.email ${{ github.event.client_payload.user_email }}
          git commit -m 'Updating submodules ${{ github.event.client_payload.smd_name }} [skip ci]'
          git push 
